In [1]:
import pandas as pd
from src.constants import CONTINUOUS_COVARIATES_PROCESSED, STATIC_COLS, TARGET_COL

# Define input variables
exogenous_vars = (
    CONTINUOUS_COVARIATES_PROCESSED + STATIC_COLS
)  # Each element must correspond to a column name
input_variables =  exogenous_vars + TARGET_COL

In [50]:
fpath_dags_diabetic_excel = "/home/gaurang/glycemic_control/data/glycaemia_project_csvs/clinical_dags/excel_files/DAG_diabetic.xlsx"

In [6]:
excel_dags_diabetic = pd.ExcelFile(fpath_dags_diabetic_excel)

In [12]:
excel_dags_diabetic.sheet_names

['knobel_urs',
 'balmer_belinda',
 'boesiger_fabienne',
 'bretscher_celine',
 'brunner_andreas',
 'fuechtbauer_laila',
 'gambini_luiza',
 'gut_lara',
 'meier_nicole',
 'meyer_martina',
 'monnerat_sophie',
 'mueller_beat',
 'rathmes_guilia',
 'refardt_julie',
 'schuetz_philipp',
 'spennato_umberto',
 'wimmer_roxana',
 'winzeler_bettina',
 'zueger_thomas',
 'UK_Essen1',
 'UK_Essen2',
 'UK_Essen3',
 'tristan_struja']

In [60]:
df1 = pd.read_csv("/home/gaurang/glycemic_control/data/glycaemia_project_csvs/clinical_dags/diabetic/balmer_belinda.csv").fillna(0)
df1[input_variables].values.shape

(16, 16)

In [52]:
df1.columns

Index(['Unnamed: 0', 'SOFA score', 'liver function', 'weight', 'height', 'bmi',
       'gcs', 'age', 'vasopresser dose', 'tube feeding', 'cmi', 'dextrose',
       'platelet level', 'PaO2/FiO2', 'renal function', 'insulin', 'glucose'],
      dtype='object')

In [33]:
covariates = [
    'sofa_24hours',
    'liver_24hours',
    'weight_kg',
    'height_cm',
    'bmi',
    'cns_24hours',
    'admission_age',
    'cardiovascular_24hours',
    'tube_feeding',
    'charlson_comorbidity_index',
    'dextrose',
    'coagulation_24hours',
    'respiration_24hours',
    'renal_24hours',
    'insulin',
    'glucose'
    ]

len(covariates)

16

In [43]:
df1.index = covariates
df1.columns = covariates

array([[0., 1., 0., 0., 0., 1., 0., 2., 0., 1., 0., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 2., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2.],
       [1., 0., 0., 0., 1., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 3.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [36]:
adj_mat = df1.to_numpy()
adj_mat


array([[0., 1., 0., 0., 0., 1., 0., 2., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 2., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 3.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [38]:
source = []
destination = []
for row in range(adj_mat.shape[0]):
    for col in range(row):
        adj_mat[row, col] = adj_mat[col, row]

In [39]:
adj_mat

array([[0., 1., 0., 0., 0., 1., 0., 2., 0., 1., 0., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 2., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2.],
       [1., 0., 0., 0., 1., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 3.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [40]:
(adj_mat == adj_mat.T).all()

True

In [46]:
df1.values

/tmp/ipykernel_3508/478824737.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df1.values = adj_mat


AttributeError: can't set attribute

In [2]:
fpath_dag = "/home/gaurang/glycemic_control/data/glycaemia_project_csvs/clinical_dags/diabetic/fuechtbauer_laila.csv"
df_dag = pd.read_csv(fpath_dag)
df_dag

Unnamed: 0  sofa_24hours  liver_24hours  weight_kg  \
0                 sofa_24hours           0.0            0.0        0.0   
1                liver_24hours           0.0            0.0        0.0   
2                    weight_kg           0.0            0.0        0.0   
3                    height_cm           0.0            0.0        0.0   
4                          bmi           0.0            0.0        0.0   
5                  cns_24hours           0.0            0.0        0.0   
6                admission_age           0.0            0.0        0.0   
7       cardiovascular_24hours           0.0            0.0        0.0   
8                 tube_feeding           0.0            0.0        0.0   
9   charlson_comorbidity_index           0.0            0.0        0.0   
10                    dextrose           0.0            0.0        0.0   
11         coagulation_24hours           0.0            0.0        0.0   
12         respiration_24hours           0.0            0.0        0.0   
13               renal_24hours           0.0            0.0        0.0   
14                     insulin           0.0            0.0        0.0   
15                     glucose           0.0            0.0        0.0   

    height_cm  bmi  cns_24hours  admission_age  cardiovascular_24hours  \
0         0.0  0.0          3.0            0.0                     0.0   
1         0.0  1.0          0.0            0.0                     0.0   
2         0.0  3.0          0.0            0.0                     0.0   
3         0.0  3.0          0.0            0.0                     0.0   
4         0.0  0.0          0.0            0.0                     0.0   
5         0.0  0.0          0.0            0.0                     0.0   
6         0.0  0.0          0.0            0.0                     0.0   
7         0.0  0.0          0.0            0.0                     0.0   
8         0.0  0.0          0.0            0.0                     0.0   
9         0.0  0.0          0.0            0.0                     0.0   
10        0.0  0.0          0.0            0.0                     0.0   
11        0.0  0.0          0.0            0.0                     0.0   
12        0.0  0.0          0.0            0.0                     0.0   
13        0.0  0.0          0.0            0.0                     0.0   
14        0.0  0.0          0.0            0.0                     0.0   
15        0.0  0.0          0.0            0.0                     0.0   

    tube_feeding  charlson_comorbidity_index  dextrose  coagulation_24hours  \
0            0.0                         0.0       0.0                  2.0   
1            0.0                         0.0       0.0                  0.0   
2            0.0                         0.0       0.0                  0.0   
3            0.0                         0.0       0.0                  0.0   
4            0.0                         0.0       0.0                  0.0   
5            1.0                         1.0       0.0                  0.0   
6            0.0                         0.0       0.0                  0.0   
7            0.0                         0.0       0.0                  0.0   
8            0.0                         0.0       0.0                  0.0   
9            0.0                         0.0       0.0                  0.0   
10           0.0                         0.0       0.0                  0.0   
11           0.0                         0.0       0.0                  0.0   
12           0.0                         0.0       0.0                  0.0   
13           0.0                         0.0       0.0                  0.0   
14           0.0                         0.0       0.0                  0.0   
15           0.0                         0.0       0.0                  0.0   

    respiration_24hours  renal_24hours  insulin  glucose  
0                   2.0            2.0      0.0      1.0  
1                   0.0            0.0  

In [4]:
from src.dataset import get_adjacency_matrix
from src.constants import INPUT_COVARIATES, TARGET_COL
import pandas as pd

In [6]:
dag1 = pd.read_csv("/home/gaurang/glycemic_control/data/glycaemia_project_csvs/clinical_dags/diabetic/balmer_belinda.csv")
dag2 = pd.read_csv("/home/gaurang/glycemic_control/data/glycaemia_project_csvs/clinical_dags/diabetic/boesiger_fabienne.csv")


In [9]:
(get_adjacency_matrix(dag1) == get_adjacency_matrix(dag2)).all()

False

In [10]:
a = get_adjacency_matrix(dag1) 

In [14]:
(a == 1).sum()/2

11.0

In [20]:
for row in range(adj_matrix.shape[0]):
    for col in range(row):
        adj_matrix[row, col] = adj_matrix[col, row]

1 0
2 0
2 1
3 0
3 1
3 2
4 0
4 1
4 2
4 3
5 0
5 1
5 2
5 3
5 4
6 0
6 1
6 2
6 3
6 4
6 5
7 0
7 1
7 2
7 3
7 4
7 5
7 6
8 0
8 1
8 2
8 3
8 4
8 5
8 6
8 7
9 0
9 1
9 2
9 3
9 4
9 5
9 6
9 7
9 8
10 0
10 1
10 2
10 3
10 4
10 5
10 6
10 7
10 8
10 9
11 0
11 1
11 2
11 3
11 4
11 5
11 6
11 7
11 8
11 9
11 10
12 0
12 1
12 2
12 3
12 4
12 5
12 6
12 7
12 8
12 9
12 10
12 11
13 0
13 1
13 2
13 3
13 4
13 5
13 6
13 7
13 8
13 9
13 10
13 11
13 12
14 0
14 1
14 2
14 3
14 4
14 5
14 6
14 7
14 8
14 9
14 10
14 11
14 12
14 13
15 0
15 1
15 2
15 3
15 4
15 5
15 6
15 7
15 8
15 9
15 10
15 11
15 12
15 13
15 14
