In [56]:
import pandas as pd
from src.constants import CONTINUOUS_COVARIATES_PROCESSED, STATIC_COLS, TARGET_COL

# Define input variables
exogenous_vars = (
    CONTINUOUS_COVARIATES_PROCESSED + STATIC_COLS
)  # Each element must correspond to a column name
input_variables =  exogenous_vars + TARGET_COL

In [50]:
fpath_dags_diabetic_excel = "/home/gaurang/glycemic_control/data/glycaemia_project_csvs/clinical_dags/excel_files/DAG_diabetic.xlsx"

In [6]:
excel_dags_diabetic = pd.ExcelFile(fpath_dags_diabetic_excel)

In [12]:
excel_dags_diabetic.sheet_names

['knobel_urs',
 'balmer_belinda',
 'boesiger_fabienne',
 'bretscher_celine',
 'brunner_andreas',
 'fuechtbauer_laila',
 'gambini_luiza',
 'gut_lara',
 'meier_nicole',
 'meyer_martina',
 'monnerat_sophie',
 'mueller_beat',
 'rathmes_guilia',
 'refardt_julie',
 'schuetz_philipp',
 'spennato_umberto',
 'wimmer_roxana',
 'winzeler_bettina',
 'zueger_thomas',
 'UK_Essen1',
 'UK_Essen2',
 'UK_Essen3',
 'tristan_struja']

In [60]:
df1 = pd.read_csv("/home/gaurang/glycemic_control/data/glycaemia_project_csvs/clinical_dags/diabetic/balmer_belinda.csv").fillna(0)
df1[input_variables].values.shape

(16, 16)

In [52]:
df1.columns

Index(['Unnamed: 0', 'SOFA score', 'liver function', 'weight', 'height', 'bmi',
       'gcs', 'age', 'vasopresser dose', 'tube feeding', 'cmi', 'dextrose',
       'platelet level', 'PaO2/FiO2', 'renal function', 'insulin', 'glucose'],
      dtype='object')

In [33]:
covariates = [
    'sofa_24hours',
    'liver_24hours',
    'weight_kg',
    'height_cm',
    'bmi',
    'cns_24hours',
    'admission_age',
    'cardiovascular_24hours',
    'tube_feeding',
    'charlson_comorbidity_index',
    'dextrose',
    'coagulation_24hours',
    'respiration_24hours',
    'renal_24hours',
    'insulin',
    'glucose'
    ]

len(covariates)

16

In [43]:
df1.index = covariates
df1.columns = covariates

array([[0., 1., 0., 0., 0., 1., 0., 2., 0., 1., 0., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 2., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2.],
       [1., 0., 0., 0., 1., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 3.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [36]:
adj_mat = df1.to_numpy()
adj_mat


array([[0., 1., 0., 0., 0., 1., 0., 2., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 2., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 3.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [38]:
source = []
destination = []
for row in range(adj_mat.shape[0]):
    for col in range(row):
        adj_mat[row, col] = adj_mat[col, row]

In [39]:
adj_mat

array([[0., 1., 0., 0., 0., 1., 0., 2., 0., 1., 0., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 2., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2.],
       [1., 0., 0., 0., 1., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 3.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [40]:
(adj_mat == adj_mat.T).all()

True

In [46]:
df1.values

/tmp/ipykernel_3508/478824737.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df1.values = adj_mat


AttributeError: can't set attribute